# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import bank_system_pb2 as protos_dot_bank__system__pb2


class BranchServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MsgDelivery = channel.unary_unary(
                '/BranchService/MsgDelivery',
                request_serializer=protos_dot_bank__system__pb2.Events.SerializeToString,
                response_deserializer=protos_dot_bank__system__pb2.Output.FromString,
                )
        self.Propogate_Deposit = channel.unary_unary(
                '/BranchService/Propogate_Deposit',
                request_serializer=protos_dot_bank__system__pb2.Event.SerializeToString,
                response_deserializer=protos_dot_bank__system__pb2.Recv.FromString,
                )
        self.Propogate_Withdraw = channel.unary_unary(
                '/BranchService/Propogate_Withdraw',
                request_serializer=protos_dot_bank__system__pb2.Event.SerializeToString,
                response_deserializer=protos_dot_bank__system__pb2.Recv.FromString,
                )
        self.getFinalBalance = channel.unary_unary(
                '/BranchService/getFinalBalance',
                request_serializer=protos_dot_bank__system__pb2.Event.SerializeToString,
                response_deserializer=protos_dot_bank__system__pb2.Event.FromString,
                )
        self.getOutput = channel.unary_unary(
                '/BranchService/getOutput',
                request_serializer=protos_dot_bank__system__pb2.Output.SerializeToString,
                response_deserializer=protos_dot_bank__system__pb2.Output.FromString,
                )
        self.getBranchProcess = channel.unary_unary(
                '/BranchService/getBranchProcess',
                request_serializer=protos_dot_bank__system__pb2.BranchProcess.SerializeToString,
                response_deserializer=protos_dot_bank__system__pb2.BranchProcess.FromString,
                )


class BranchServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MsgDelivery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Propogate_Deposit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Propogate_Withdraw(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getFinalBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getOutput(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getBranchProcess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BranchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MsgDelivery': grpc.unary_unary_rpc_method_handler(
                    servicer.MsgDelivery,
                    request_deserializer=protos_dot_bank__system__pb2.Events.FromString,
                    response_serializer=protos_dot_bank__system__pb2.Output.SerializeToString,
            ),
            'Propogate_Deposit': grpc.unary_unary_rpc_method_handler(
                    servicer.Propogate_Deposit,
                    request_deserializer=protos_dot_bank__system__pb2.Event.FromString,
                    response_serializer=protos_dot_bank__system__pb2.Recv.SerializeToString,
            ),
            'Propogate_Withdraw': grpc.unary_unary_rpc_method_handler(
                    servicer.Propogate_Withdraw,
                    request_deserializer=protos_dot_bank__system__pb2.Event.FromString,
                    response_serializer=protos_dot_bank__system__pb2.Recv.SerializeToString,
            ),
            'getFinalBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.getFinalBalance,
                    request_deserializer=protos_dot_bank__system__pb2.Event.FromString,
                    response_serializer=protos_dot_bank__system__pb2.Event.SerializeToString,
            ),
            'getOutput': grpc.unary_unary_rpc_method_handler(
                    servicer.getOutput,
                    request_deserializer=protos_dot_bank__system__pb2.Output.FromString,
                    response_serializer=protos_dot_bank__system__pb2.Output.SerializeToString,
            ),
            'getBranchProcess': grpc.unary_unary_rpc_method_handler(
                    servicer.getBranchProcess,
                    request_deserializer=protos_dot_bank__system__pb2.BranchProcess.FromString,
                    response_serializer=protos_dot_bank__system__pb2.BranchProcess.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'BranchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BranchService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MsgDelivery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BranchService/MsgDelivery',
            protos_dot_bank__system__pb2.Events.SerializeToString,
            protos_dot_bank__system__pb2.Output.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Propogate_Deposit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BranchService/Propogate_Deposit',
            protos_dot_bank__system__pb2.Event.SerializeToString,
            protos_dot_bank__system__pb2.Recv.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Propogate_Withdraw(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BranchService/Propogate_Withdraw',
            protos_dot_bank__system__pb2.Event.SerializeToString,
            protos_dot_bank__system__pb2.Recv.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getFinalBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BranchService/getFinalBalance',
            protos_dot_bank__system__pb2.Event.SerializeToString,
            protos_dot_bank__system__pb2.Event.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getOutput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BranchService/getOutput',
            protos_dot_bank__system__pb2.Output.SerializeToString,
            protos_dot_bank__system__pb2.Output.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getBranchProcess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BranchService/getBranchProcess',
            protos_dot_bank__system__pb2.BranchProcess.SerializeToString,
            protos_dot_bank__system__pb2.BranchProcess.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
